// The share card every page points at: the wordmark on jet, generated by
// app/opengraph-image.tsx.
//
// Next replaces a parent's `openGraph` wholesale when a child defines its
// own, so the root file-based image silently vanished from every page
// that set a title — which is why a shared /portfolio link scraped a
// random video frame instead of showing the logo. Each page spreads this
// in, so the card is the same wherever the link is pasted.
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 800,
  height: 800,
  alt: "VEKTO",
} as const;
